// PWA surface of the chat (spec 045 FR-021, FR-023, FR-024), pure and DOM-free:
// the host (doctiling-web) serves what these functions return from its own
// route handlers (`/{locale}/chat/manifest.webmanifest`, `/{locale}/chat/sw.js`,
// the offline page) and copies `public/icons/*` next to them.

import type { Language } from './i18n';

/** Mirror of @doctiling/brand lightColors (tests assert the parity). */
export const CHAT_THEME_COLOR = '#798A75';
export const CHAT_BACKGROUND_COLOR = '#FBFAF9';

const COPY = {
  en: {
    description: "Ask your organisation's knowledge bases from your phone.",
    offlineTitle: 'No connection',
    offlineLead: 'Doctiling Chat needs a connection to your organisation.',
    offlineBody: 'Nothing is stored on this device, so there is nothing to show while offline.',
    retry: 'Retry',
  },
  es: {
    description: 'Pregunta a las bases de conocimiento de tu organización desde el teléfono.',
    offlineTitle: 'Sin conexión',
    offlineLead: 'Doctiling Chat necesita conexión con tu organización.',
    offlineBody: 'Nada se guarda en este dispositivo, así que no hay nada que mostrar sin red.',
    retry: 'Reintentar',
  },
} as const satisfies Record<Language, Record<string, string>>;

const trimSlashes = (s: string) => s.replace(/\/+$/, '');
const ensureSlash = (s: string) => (s.endsWith('/') ? s : `${s}/`);

export type ManifestOptions = {
  /** Where the installed app opens, e.g. `/es/chat`. */
  startUrl: string;
  /** Navigation scope of the installed app, e.g. `/es/chat/` (FR-021). Also the manifest `id`. */
  scope: string;
  /** URL prefix of the copied icons, e.g. `/chat/icons` (default). */
  iconsBase?: string;
};

export type WebManifest = {
  id: string;
  name: string;
  short_name: string;
  description: string;
  scope: string;
  start_url: string;
  display: 'standalone';
  orientation: 'portrait';
  background_color: string;
  theme_color: string;
  lang: Language;
  dir: 'ltr';
  launch_handler: { client_mode: 'navigate-existing' };
  icons: Array<{ src: string; sizes: string; type: 'image/png'; purpose: 'any' | 'maskable' }>;
};

export function manifestFor(locale: Language, { startUrl, scope, iconsBase = '/chat/icons' }: ManifestOptions): WebManifest {
  const scoped = ensureSlash(scope);
  const icons = trimSlashes(iconsBase);
  return {
    id: scoped,
    name: 'Doctiling Chat',
    short_name: 'Chat',
    description: COPY[locale].description,
    scope: scoped,
    start_url: startUrl,
    display: 'standalone',
    orientation: 'portrait',
    background_color: CHAT_BACKGROUND_COLOR,
    theme_color: CHAT_THEME_COLOR,
    lang: locale,
    dir: 'ltr',
    launch_handler: { client_mode: 'navigate-existing' },
    icons: [
      { src: `${icons}/icon-192.png`, sizes: '192x192', type: 'image/png', purpose: 'any' },
      { src: `${icons}/icon-512.png`, sizes: '512x512', type: 'image/png', purpose: 'any' },
      { src: `${icons}/maskable-192.png`, sizes: '192x192', type: 'image/png', purpose: 'maskable' },
      { src: `${icons}/maskable-512.png`, sizes: '512x512', type: 'image/png', purpose: 'maskable' },
    ],
  };
}

export type ServiceWorkerOptions = {
  /** Scope the worker is registered with, e.g. `/es/chat/`. Navigations outside it are left alone. */
  scope: string;
  /** Static page served by the host for the navigation fallback, e.g. `/es/chat/offline.html`. */
  offlineUrl: string;
  /** Package version: every release gets its own caches. */
  version: string;
  /** Extra URLs to precache at install (icons, manifest). The offline page is always included. */
  precache?: string[];
  /** URL prefixes of versioned static assets, cached first. Default: Next's `/_next/static/` and `/chat/`. */
  staticPrefixes?: string[];
};

const js = (v: unknown) => JSON.stringify(v);

/**
 * Source of the service worker. Rules (FR-023, FR-024): navigations inside the
 * scope are network-first and fall back to the offline page; `/api/*`, any
 * non-GET and any request carrying `Authorization` are never intercepted nor
 * cached (business data never lives on the device; the session cookie travels
 * only to the network); versioned static assets are cache-first; a new worker
 * waits until the page posts SKIP_WAITING — no skipWaiting on install.
 */
export function serviceWorkerSource({ scope, offlineUrl, version, precache = [], staticPrefixes }: ServiceWorkerOptions): string {
  const scoped = ensureSlash(scope);
  const shell = [...new Set([offlineUrl, ...precache])];
  const prefixes = staticPrefixes ?? ['/_next/static/', trimSlashes(scoped.replace(/^\/(en|es)\//, '/')) + '/'];
  return `/* Doctiling Chat service worker ${version} (spec 045 FR-023, FR-024). Generated by @doctiling/chat/pwa. */
const VERSION = ${js(version)};
const SCOPE = ${js(scoped)};
const SHELL_CACHE = 'doctiling-chat-shell-' + VERSION;
const ASSET_CACHE = 'doctiling-chat-assets-' + VERSION;
const OFFLINE_URL = ${js(offlineUrl)};
const SHELL = ${js(shell)};
const STATIC_PREFIXES = ${js(prefixes)};

function neverCache(request, url) {
  if (request.method !== 'GET') return true;
  if (request.headers && request.headers.has && request.headers.has('authorization')) return true;
  if (url.pathname.startsWith('/api/')) return true;
  if (url.pathname.endsWith('/sw.js')) return true;
  return false;
}

function isStaticAsset(url) {
  if (url.pathname === OFFLINE_URL) return false;
  for (const p of STATIC_PREFIXES) if (url.pathname.startsWith(p)) return /\\.(js|css|png|svg|ico|woff2?|webmanifest)$/.test(url.pathname);
  return false;
}

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(SHELL_CACHE).then((cache) =>
      Promise.all(
        SHELL.map((path) =>
          cache.add(new Request(path, { cache: 'reload', credentials: 'same-origin' })).catch(() => {
            /* a missing icon must not break the install */
          }),
        ),
      ),
    ),
  );
  // Deliberately no self.skipWaiting(): the page decides (FR-024).
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('doctiling-chat-') && k !== SHELL_CACHE && k !== ASSET_CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') self.skipWaiting();
});

async function networkFirstNavigation(request) {
  try {
    return await fetch(request);
  } catch {
    const cache = await caches.open(SHELL_CACHE);
    const offline = await cache.match(OFFLINE_URL);
    if (offline) return offline;
    return new Response('offline', { status: 503, headers: { 'Content-Type': 'text/plain' } });
  }
}

async function cacheFirstAsset(request) {
  const cache = await caches.open(ASSET_CACHE);
  const hit = await cache.match(request);
  if (hit) return hit;
  const res = await fetch(request);
  // Same-origin responses only ('basic' in browsers, 'default' in tests); never an opaque one.
  if (res && res.ok && (res.type === 'basic' || res.type === 'default')) cache.put(request, res.clone()).catch(() => {});
  return res;
}

self.addEventListener('fetch', (event) => {
  const request = event.request;
  let url;
  try {
    url = new URL(request.url);
  } catch {
    return;
  }
  if (url.origin !== self.location.origin) return;
  if (neverCache(request, url)) return; // falls through to the network, no respondWith
  if (request.mode === 'navigate') {
    // Only the chat's own pages get the offline fallback; the studio is not this worker's business.
    if (url.pathname === SCOPE.slice(0, -1) || url.pathname.startsWith(SCOPE)) event.respondWith(networkFirstNavigation(request));
    return;
  }
  if (isStaticAsset(url)) {
    event.respondWith(cacheFirstAsset(request));
  }
});
`;
}

const escapeHtml = (s: string) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

/** The static page the worker serves when a navigation fails offline. Bilingual copy, one language per `locale`. */
export function offlineHtml(locale: Language): string {
  const c = COPY[locale];
  return `<!doctype html>
<html lang="${locale}">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
    <meta name="theme-color" content="${CHAT_THEME_COLOR}" />
    <meta name="robots" content="noindex" />
    <title>Doctiling Chat</title>
    <style>
      :root { --bg: #fbfaf9; --fg: #212e3b; --muted: #53606e; --primary: #798a75; --primary-fg: #f6f7f9; }
      @media (prefers-color-scheme: dark) {
        :root { --bg: #181f25; --fg: #e8e2d9; --muted: #b0a99b; --primary: #92a58d; --primary-fg: #181f25; }
      }
      html, body { height: 100%; margin: 0; background: var(--bg); color: var(--fg); font-family: Inter, system-ui, -apple-system, 'Segoe UI', sans-serif; }
      main { min-height: 100%; display: flex; flex-direction: column; justify-content: center; align-items: center; text-align: center; padding: 2rem 1.5rem calc(2rem + env(safe-area-inset-bottom)); box-sizing: border-box; }
      h1 { font-family: Fraunces, Georgia, serif; font-weight: 600; font-size: 1.5rem; margin: 1rem 0 0.5rem; }
      p { color: var(--muted); max-width: 28rem; margin: 0.25rem 0; }
      button { margin-top: 1.5rem; min-height: 44px; padding: 0 1.5rem; border: 0; border-radius: 10px; background: var(--primary); color: var(--primary-fg); font: inherit; font-weight: 500; }
      svg { width: 48px; height: 48px; color: var(--muted); }
    </style>
  </head>
  <body>
    <main>
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
        <path d="M12 20h.01" /><path d="M8.5 16.4a5 5 0 0 1 7 0" /><path d="M5 12.9a10 10 0 0 1 5.2-2.7" /><path d="M19 12.9a10 10 0 0 0-2.1-1.6" /><path d="M2 8.8A15 15 0 0 1 8.4 5.4" /><path d="M22 8.8a15 15 0 0 0-6.1-3.3" /><path d="m2 2 20 20" />
      </svg>
      <h1>${escapeHtml(c.offlineTitle)}</h1>
      <p>${escapeHtml(c.offlineLead)}</p>
      <p>${escapeHtml(c.offlineBody)}</p>
      <button type="button" onclick="location.reload()">${escapeHtml(c.retry)}</button>
    </main>
    <script>
      addEventListener('online', function () { location.reload(); });
    </script>
  </body>
</html>
`;
}
